### PR TITLE
-Modified view deck so you tap the nav bar to close

### PR DESCRIPTION
**Pull request by kcharwood**
-Refactored some naming conventions while I was there

First pass at making it possible to tap anywhere navigation bar to close it.
Also removed the center 'button', and converted it to an overlay view with a tap gesture recognizer.

### CODE REVIEW

**Comment by kcharwood** [comment]
Fasted code review EVER

**Comment by ghost** [comment]
You mean that big ass button that covers the entire centre deck is now gone!? That was the best part!

**Comment by larsacus** [comment]
I actually _did_ look at the diff. Now Katie has nothing to look forward to looking at on this project.

**Comment by ghost** [comment]
I will point you to this: https://github.com/mutualmobile/ViewDeck/pull/3

**Comment by larsacus** [comment]
I told you to re-submit it. The request diverged from the master when I had to fix all of the _other_ pull requests.

**Comment by ghost** [comment]
Whoops.

**Comment by larsacus** [comment]
Yeah I'm lazy. Usually pull request merges require clicking one button. ...unless it can't be automatically merged :+1:

**Pull request merged**
